spring:
  datasource:
    url: jdbc:mysql://localhost:3306/curso_udemy
    name: curso_udemy
    username: root
    password: yz450f
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update   
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
         
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  