spring:
  datasource:
    url: jdbc:mysql://localhost:3306/curso_udemy?useSSL=false
    name: curso_udemy
    username: root
    password: yz450f
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update   
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
         
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
        type: trace 
        dialect: org.hibernate.dialect.MySQL5Dialect
  thymeleaf:
    cache: false
logging:
  level:
    org:
      hibernate:
        sql: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder:TRACE